server:
  port: 8089

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver


thymeleaf:
  cache=false
mybatis:
  mapper-locations: classpath:mapping/*mapper.xml
  type-aliases-package: com.example.demo_log_demo.bean

logging.level.org.springframework.boot.autoconfigure: ERROR



